#!/usr/bin/env node

var originalDir = __dirname;
process.chdir(process.cwd());

var fs = require('fs');
var commandLine = require('commander');
var configManager = require('./src/configManager');
var postProcess = require('./src/server');
var command = 'phantomjs "#{cwd}/src/phantomRunner.js" "#{cwd}" "#{url}" \'#{config}\' --web-security=no --local-to-remote-url-access=yes --load-images=no';
var config;

commandLine
  .version(require('./package.json').version)
  .option('-u --url [value]', 'URL to process')
  .option('-c --config [value]', 'Path to JSON configuration file (see https://github.com/JamieMason/Asterisk#config)')
  .parse(process.argv);

if(commandLine.url) {
  configManager.init({
    executionDir: originalDir,
    binDir: __dirname,
    program: commandLine
  });

  config = configManager.getConfig();
  command = command.split('#{cwd}').join(__dirname).split('#{url}').join(commandLine.url).split('#{config}').join(JSON.stringify(config));

  require('child_process').exec(command, function(error, stdout, stderr) {
    error === null ? postProcess.processBrowserOutput(stdout, config) : console.error(error);
  });
}
